dist: xenial

services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -U postgres -c "create user decide1530 password 'decide1530'"
  - psql -U postgres -c "create database decide130 owner decide1530"
  - psql -U postgres -c "ALTER USER decide1530 CREATEDB"
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install codacy-coverage
script:
  - cd decide
  - coverage run --branch --source=. ./manage.py test store --keepdb 
  - coverage xml
  - python-codacy-coverage -r coverage.xml

